# -*- coding: utf-8 -*-
"""PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5tGx_NPn6B6F4y4JWN1nZuDJt_QqhKm
"""

#RUN ONLY IF THERE IS NO PLANS OF IMPORTING DATA VIA INTERNET OR MANUALLY
from google.colab import drive
import pandas as pd


drive.mount('/content/drive')

file_path = '/content/drive/My Drive/ip/IPPROJECT.xlsx'
df = pd.read_excel(file_path)
print(df)

print(line)
print('')

#PROJECT BY  ContactEase
import pandas as pd                                                             #for using Dataframe
import numpy as np                                                              #For using nill and NaN values
line="========================================\n"


print(line)
print("          Welcome to ContactEase!       ")
print(line)
print("Your Personal Contact Management System")
print(line)
print("With ContactEase, you can easily add, update, delete,")
print("and search your contacts, all in one place.")
print("Manage your contacts efficiently and securely.")
print(line)
print("Let's get started!")
print(line)
print("Do you have a existing contact ")
print(line)
conopt=input('Do You Want To Import')
if conopt=='yes' or 'y' in conopt or 'Y' in conopt:                             #entering the choice of importing
  if conopt=="yes" or conopt=='YES' or "y"in conopt:                            #if they want to import
    importopt=input("CSV , Excel  OR MANUALY ")
    if importopt =="excel" or importopt=='Excel' or importopt=="EXCEL":
      link=input('ENTER EXCEL LINK')
      df = pd.read_csv(link)
    elif importopt =="CSV" or importopt=='csv' or importopt=="Csv":
      link=input('ENTER CSV LINK')
      df = pd.read_csv(link)
    else:
      num=int(input('enter the number of contacts to be imported'))
      for i  in range(num):                                                     #for loop is used for executing the programs as much number the user imports                                  #to check the entered number is correct or not
          name = input("Enter name:")
          phone = int(input("Enter phone number: "))
          if phone>1111111111 and phone<9999999999:
            print("NUMBER VERIFIED")
          else:
            print("This is NOT a 10-digit number.")
          email = input("Enter email: ")
          profession= input("Enter profession:")
          ADDRESS=input("Enter ADDRESS:")
          new_contact= pd.DataFrame[[name, phone, email,profession,ADDRESS]]
          contacts_df = pd.contact([contacts_df, new_contact], ignore_index=True)
          contacts_df.to_csv('contacts.csv', index=False)
          print("Contact added successfully!")                                  # Load the CSV file into a DataFrame
while True:                                                                     #the contact need to run until the user wants to break
  print('1.DISPLAY YOUR CONTACTS ',                                             #to display a menu driven contact
        '2.DISPLAY FILTER SEARCH OF  ALL CONTACTS',
        '3.FIND A CONTACT ','4.CHANGE A CONATACT NUMBER ',
        '5.ADD A PERSONS CONTACT','6.DELETE A CONTACT ',
        '7.CLEAR ALL CONTACTS ','8.EXIT',sep='\n')

chi=input("ENTER YOUR OPTION")
if chi=='1' or chi=='DISPLAY YOUR CONTACTS' or chi=='Display your contacts' or "contacts" in chi:
    print(df)                                                                   #Displaying the contacts in a tabular form

elif chi=='2' or 'Fil' in chi or "fil" in chi or "FIL" in chi:                  #Displaying the contacts in a t sorted form
    while True:
      print(df[[fil1,]])

elif chi=='3' or chi in 'find':                                                 #find a contact where it is present in the dic
    sname=input('enter the persons name to be scearched ')                      #sname a new varible used to get the name to be deleted
    if sname in df:
      print("the contact number is",df.get(sname))
    else:
      print("sorry we could not find it")

elif chi=='4' or 'C' in chi:                                                   #To add a change a number
    h=input("enter the name ")
    newno=int(input('enter the new number '))
    con[h]=newno
    print("successfully changed")
elif chi=='5' or 'Add' in chi or "a" in chi:                                  #to add a new person
    num=int(input("number of friends"))
    for i  in range(num):
      chio=int(input("enter the new number"))
      n=input('enter the name')
      if no>= 1111111111 and no<= 9999999999:
        con[n]=chio
      else:
        print("check your number please ")
        numbe=int(input("enter the phone number"))
        con[name]=numbe
      print("successfully added")
elif chi=='8' or 'Exit' in chi or 'exit' in chi:                              #to exit
    break
elif chi=="6" or "Del" in chi:                                                #to delete a person from
    delname=input("enter the name to be deleted ")
    del(con[delname])
elif chi=='7' or 'cle' in chi:                                                #to clean all contacts
    con.clear()
    print("ALL CLEAN")
else:                                                                         #if the input fails
    print('input failed !! Try again')

import truecallerpy as truecaller

pip install truecallerpy

sudo truecallerpy login

